// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwyudvoecxvpkosnyxmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3eXVkdm9lY3h2cGtvc255eG1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEwNDA2MDcsImV4cCI6MjA4NjYxNjYwN30.nGhOGcZlaN6OPRv2fufBJAj19b1YuVVRqsLGIoY4Ph0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});